### ISSUE TITLE
[master task] SQL tables requests and roadmap

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#619]
This issue is tracking requested virtual tables. If you would like to suggest a new table or discuss the need for a new table please comment on this issue. If you would like to implement one of the tables or need a focused discussion please open a separate issue dedicated to that virtual table.

This issue tracks requested/planned additions to the available SQL tables in osquery. If you would like to suggest/discuss a new SQL table please comment on this issue. If you would like to implement one of the tables or need a focused discussion please open a separate issue dedicated to that table.
#### Shared (cross-platform) tables:
- [ ] Exported NFS shares (linux, ~~OS X~~)
- [ ] Binary "strings" for a specific path
- [x] ~~MDNS settings/cache~~
- [x] FDE status (fdesetup/~~Filevault on OS X~~) Issue: #913, PR: #913
- [x] Network settings (~~forwarding~~/promisc/~~nameservers~~)
- [x] ~~Browser plugins/extensions~~
- [ ] Unpacked / developer-mode chrome extensions
- [x] ~~osquery-IO utilization~~
- [x] sleuth kit timeline
- [ ] log files (apache logs, system logs, etc)
- [ ] shared memory (~~linux~~, OS X (zpages))
- [x] ~~process memory maps~~ (~~linux~~, ~~OS X~~)
- [x] ~~group membership~~
- [ ] general systems information (#1447)
- [x] timezone in time table (#1547)
- [x] configured printers (#1566)
- [ ] static or DHCP indicator for `interface_addresses` (#1575)
- [ ] `file_regex` table for applying greps across selected file targets (#1692)
- [ ] `ssdeep` support in hashing table (#1775)
- [ ] User entries in the sudoers file (#2024)
#### OS X Tables:
- [x] Crashed process reports
- [x] Package install history (/Library/Receipts/InstallHistory.plist) (#1922)
- [x] Wifi saved info and details (/Library/Preferences/SystemConfiguration/com.apple.airport.preferences.plist)
- [x] ~~xattr "wherefrom" for downloaded items in select directories~~ GH-653
- [ ] EAPO Client module (/Library/Preferences/SystemConfiguration/com.apple.network.eapolclient.configuration.plist)
- [X] ~~Managed client information panes~~
- [ ] packet/pf/bp firewall (#1521)
- [x] ~~defaults read table with path to plist trigger~~
- [x] ~~blessed boot directory/file using nvram settings~~ (available as `kernel_info`)
- [x] ~~Block devices (parity with Linux)~~
- [x] macho signature (joinable, like file/hash) GH-800
- [x] more signature (and signer) details for machos and related signed blobs  #(#1770)
- [x] ~~authorization DB config~~
- [ ] macports packages
- [ ] kernel_extension_plugins and FileSystem-based extensions
- [ ] `interface_details` service order & primary interface indicator (#1568)
- [ ] Gatekeeper entitlements status (#2042)
#### Linux Tables:
- [x] iptables
- [x] /boot directory/configuration
- [ ] TPM information
- [ ] bonds #1173
- [ ] Fedora's DNF (yum replacement) #1515 
#### Deep systems/esoteric tables:
- [x] EFI platform metadata (OS X: #1317)
- [x] Bootloader metadata, GUID-PT/paths, etc.
- [ ] EFI/UEFI variables
- [ ] EDID information
- [ ] Supported/attached bus information
- [x] ~~DMI/SMBIOS data~~
- [x] ~~ACPI tables~~
- [ ] BIOS Extensions
- [x] SMC information
- [ ] memory regions (~~linux~~, OS X)
- [ ] memory locking MSRs
#### Existing table additions:

Tables that exist, but need hi-priority columns.
- [ ] rpm_packages: add package signatures
- [x] processes/file: on OS X display binary signature
- [x] Add support for reading fish history in `shell_history` table (#1417)
- [ ] add "focused" attribute to `application_usage` on OS X (#1315)
- [x] add kext signature to `kernel_extensions` table on OS X (#1462)
#### Existing table modifications (column depredations/aliases)
- [x] `on_disk` in the `processes` table should be `path_exists` or `binary_exists` (#1661)
#### Kernel-introspection-enabled tables:

Tables that use the OS X kernel extension or the not-yet-developed Linux kernel module. In some cases the BSD audit framework can suffice.
- [x] Process start/stop
- [ ] Select system calls tables
- [x] Socket opens
#### Low-priority recommendations:
- [ ] High-IO/performance processes/executables
#### Anti-pattern tables:

 These are tables that are not appropriate for osquery as it exists today. This does not mean these tables are forever blacklisted, but they require considerable discussion or are more appropriate as modules or extensions and not as part of the core tables.
- Browser (chrome, firefox, safari) history (#22, #1691) this is very private information

**Comment by theopolis** [comment]
List of OS X configuration reporters (and their table mapping or priority):

| Reporter | Exists/Priority | Methods/Issue |
|-------------|------------|---------------------|
`SPAirPort` |
`SPApplications` | `apps` |
`SPAudio` |
`SPBluetooth` |
`SPCamera` | `pci_devices` | driver = "CMRA"
`SPCardReader` | `usb_devices` | Product decoding in usb_devices is wrong
`SPComponent` | low | lists media-decoders
`SPConfigurationProfile` | high | 
`SPDeveloperTools` | n/a |
`SPDiagnostics` | ??? |
`SPDisabledApplications` | ??? | 
`SPDiscBurning` | ??? |
`SPDisplays` | low |
`SPEthernet` | `network_interfaces`? | 
`SPExtensions` | `kernel_extensions` | includes more details
`SPFibreChannel` | ??? |
`SPFireWire` | ??? |
`SPFirewall` | alf
`SPFont` | n/a |
`SPFrameworks` | n/a |
`SPHardwareRAID` | n/a |
`SPInstallHistory` | `package_receipts` |
`SPLogs` | not sure |
`SPManagedClient` | high |
`SPMemory` | low |
`SPNetworkLocation` | n/a |
`SPNetwork` | `network_interfaces`  |
`SPNetworkVolume` | `mounts` |
`SPOS` | ??? |
`SPPCI` | `pci_devices` |
`SPParallelATA` | `block_devices` |
`SPParallelSCSI` | `block_devices` |
`SPPlatform` | ??? |
`SPPower` | low |
`SPPrefPane` | med |
`SPPrinters` | low |
`SPPrintersSoftware` | med |
`SPSAS` | ??? |
`SPI` | ??? |
`SPSerialATA` | `block_devices`* | "content" string missing, uses Vol UUID
`SPStartupItem` | `startup_items` |
`SPStorage` | `block_devices` |
`SPSync` | ??? |
`SPThunderbolt` | `pci_devices` | not sure if TB devices are listed
`SPUSB` | `usb_devices` |
`SPUniversalAccess` | med |
`SPWWAN` | ??? |

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by mike-myers-tob** [comment]
FYI, for #1521 in the above list (a `pf` table), we developed this functionality in an extension. But ours  works for Linux and Windows too (referencing the corresponding native firewalls in each). https://github.com/trailofbits/osquery-extensions/tree/master/firewall

**Comment by fmanco** [comment]
This issue is old and doesn't look to be up-to-date so I'm going to close. If you care about a feature in here open a [Feature Request](https://github.com/facebook/osquery/issues/new?template=Feature_Request.md). Those are going to be tagged with the [wishlist](https://github.com/facebook/osquery/labels/wishlist) label which makes them easier to find and track.
