### ISSUE TITLE
[master task] event pubsub requests and roadmap

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#622]
This issue tracks requested/planned additions to the eventing pubsub system in osquery. If you would like to suggest/discuss a new event publisher and/or subscriber please comment on this issue. If you would like to implement one of the features or need a focused discussion please open a separate issue dedicated to that feature.

Shared (cross-platform) event publishers:
- [ ] Network packet flows (libpcap)
- [ ] Selected syscalls from kernel mode
- [x] Process exec\* calls from kernel mode

Linux event publishers:
- [ ] Netlink network changes

**Comment by theopolis** [comment]
How do we feel about adding the PR for network/flow information using libpcap and requiring an explicit switch to turn it on? After a lot of thought I feel that the capability is not inherently malicious or a privacy concern.

An administrator or deployment configuration can use the capability maliciously sure, but if that's the goal osquery would not be their answer to boot.

I don't want the libpcap PR to get lost or lag behind the general eventing development. It's a valuable tool if you'd like to sample a production network service deployment or sample flow data from client-based build hosts or CI/latency regression testing.

**Comment by marpaia** [comment]
I'm all for merging that in. I think it's a valuable capability.

**Comment by theopolis** [comment]
Why was this closed? Are we tracking these somewhere else?

**Comment by theopolis** [comment]
See the discussion about kqueue/kevent userland APIs for FreeBSD and OS X: https://github.com/facebook/osquery/issues/1169

**Comment by marpaia** [comment]
I thought this was something else when I was doing my issue cleanup yesterday, my b.

**Comment by marpaia** [comment]
Nailed the process exec from kernel mode in #1330

**Comment by theopolis** [comment]
This isn't being used any longer, will close and track large publisher feature requests in dedicated issues.
